softlogo_shop.basket:
    path:     /
    defaults: { _controller: "SoftlogoShopBundle:Basket:basket" }

softlogo_shop.order:
    path:     /
    defaults: { _controller: "SoftlogoShopBundle:Basket:order" }
